### ISSUE TITLE
Timeline for open source

### ISSUE THREAD

**Issue by wowfisch** [chreisinger/ViLGOD#1]
Hi Christian,

Thank you for your work! Do you have an estimated timeline for when you might open source ViLGOD?

Best,
Tommy

**Comment by chreisinger** [comment]
Hello, 

thank you for your interest. We are working on it and will release the code before BMVC 2024, i.e., within 2 to 3 months.

Best regards,
Christian

**Comment by wowfisch** [comment]
@chreisinger Thanks for your reply!
